### ISSUE TITLE
404 not Found

### ISSUE THREAD

**Issue by SunWeiLin-Lynne** [he-dhamo/graphto3d#12]
Hi, when I want to download the checkpoint for the training model and the Atlasnet weight, I perform "chmod + x ./download_checkpoints.sh & ./download_checkpoints.sh and the same "404 not found" also appears. How did you solve it?
![image](https://user-images.githubusercontent.com/109327369/192076802-ffb9f529-c92c-4656-8666-fd46e23de240.png)

**Comment by he-dhamo** [comment]
Hi there,

I apologize for the inconvenience, caused by some server changes in the lab. You can find the checkpoints here:
https://drive.google.com/drive/folders/1RbNUpHLQiY1zskd0buAgvl-yFwnD9N8M?usp=sharing

**Comment by SunWeiLin-Lynne** [comment]
Okay thanks, but I didn't find the Atlasnet weight file "model_70.pth" either. Has its address changed?

**Comment by SunWeiLin-Lynne** [comment]
Okay thanks, but I didn't find the Atlasnet weight file "model_70.pth" either. Has its address changed?

**Comment by he-dhamo** [comment]
there is an atlasnet folder in the drive link above that contains model_70.pth
