### ISSUE TITLE
3RScan dataset folder

### ISSUE THREAD

**Issue by SunWeiLin-Lynne** [he-dhamo/graphto3d#13]
Hello, I am a newbie and I would like to know if these two folders are the same and if both hold the 3RScan dataset.
![image](https://user-images.githubusercontent.com/109327369/193183055-6701a78e-8df1-49e2-9d9b-54957c269729.png)
![image](https://user-images.githubusercontent.com/109327369/193183061-bee44f66-6ede-4bdf-9f0a-8fe91282a68d.png)

**Comment by thearkamitra** [comment]
Both of them are pointing to the same dataset location.
