### ISSUE TITLE
point cloud object generation

### ISSUE THREAD

**Issue by SharryRay** [he-dhamo/graphto3d#14]
Hi, thank you for your amazing work. I trained your main model with shared shape and layout embedding, the accuracy is the same as the paper, but when I visualize the point cloud object, the quality of point cloud generation is not good. I followed the steps in the readme, am I missing any details?
![image](https://user-images.githubusercontent.com/46341500/196952587-36d0964d-5ed0-4165-ab96-e2ba7d64111d.png)

![image](https://user-images.githubusercontent.com/46341500/196952242-f9310cf9-fe4b-4f39-8a5c-5e10e93d28de.png)
![image](https://user-images.githubusercontent.com/46341500/196952351-c6f1221c-55ef-4ef0-bf55-d5d7266063eb.png)

**Comment by Mr-Faceless** [comment]
Hello,I see you close the question,do you fix this problem?
Could you please share the visualize method with me?
Thanks a lot!
