### ISSUE TITLE
Dataset bug

### ISSUE THREAD

**Issue by caixiaoniweimar** [he-dhamo/graphto3d#18]
Hi Helisa,

thanks for the amazing work. I found there might be a bug here: https://github.com/he-dhamo/graphto3d/blob/12e352078ba48327f4bedde86f4b0b07d963e548/dataset/dataset.py#L489 `obj_points[i] = obj_pointset` should be inside the for-schleife. Otherwise, it can only learn one shape of a scene,right? Please correct me if I misunderstood. Thanks,

Regards,
Cai.

**Comment by he-dhamo** [comment]
Hi Cai, well spotted, thanks for letting us know. We always used the option *with_feats = True* for our paper, therefore we didn't notice this bug in the code release.
