### ISSUE TITLE
Error while downloading checkpoints

### ISSUE THREAD

**Issue by zohairhadi** [he-dhamo/graphto3d#6]
Hello,

When downloading the checkpoints using the bash file **download_checkpoints.sh**, I get the following error.

### Error:
```
ERROR: cannot verify campar.in.tum.de's certificate, issued by ‘CN=DFN-Verein Global Issuing CA,OU=DFN-PKI,O=Verein zur Foerderung eines Deutschen Forschungsnetzes e. V.,C=DE’:
  Unable to locally verify the issuer's authority.
To connect to campar.in.tum.de insecurely, use `--no-check-certificate'.
unzip:  cannot find or open final_checkpoints.zip, final_checkpoints.zip.zip or final_checkpoints.zip.ZIP.
mkdir: atlasnet: File exists
mv: rename model_70.pth to ./atlasnet/model_70.pth: No such file or directory
```

### Steps to reproduce:

- conda create --name g2s_env python=3.7 --file requirements.txt 
- conda activate g2s_env          # activate virtual environment
- conda install pytorch==1.2.0 cudatoolkit=10.0 -c pytorch
- pip install tensorboardx graphviz plyfile open3d==0.9.0.0 open3d-python==0.7.0.0 
- export PYTHONPATH="$PWD"

Then download the checkpoints using the following command to get the error:

> chmod +x ./download_checkpoints.sh && ./download_checkpoints.sh

### Environment:

- macOS 12.0.1
- Python 3.7.13

**Comment by he-dhamo** [comment]
Please find the checkpoints here:
https://drive.google.com/drive/folders/1RbNUpHLQiY1zskd0buAgvl-yFwnD9N8M?usp=sharing
