### ISSUE TITLE
404 Not Found nginx/1.18.0 (Ubuntu)

### ISSUE THREAD

**Issue by 2WangZhen3** [he-dhamo/graphto3d#7]
Execute chmod +x ./download_metadata_3rscan.sh && ./download_metadata_3rscan.sh, or
             chmod +x ./download_3dssg.sh && ./download_3dssg.sh, and 404 not fuound appears.

**Comment by Luffy212** [comment]
Hi, I have the same problem, have you solved it?

**Comment by he-dhamo** [comment]
Hi there, there have been some migrations in our servers and therefore the download links are not valid anymore. 

3DSSG, is now stored here: https://campar.in.tum.de/public_datasets/3DSSG/3DSSG.zip   
and the label subset we train on: https://campar.in.tum.de/public_datasets/3DSSG/3DSSG_subset.zip   
README: https://campar.in.tum.de/public_datasets/3DSSG/README.md

For 3RScan please contact the respective authors.

**Comment by SunWeiLin-Lynne** [comment]
Hi, when I want to download the checkpoint for the training model and the Atlasnet weight, I perform "chmod + x ./download_checkpoints.sh & ./download_checkpoints.sh and the same "404 not found" also appears. How did you solve it?
![image](https://user-images.githubusercontent.com/109327369/192076741-479d2ca6-21b1-4ada-b86c-1821f2b57a16.png)

**Comment by he-dhamo** [comment]
https://github.com/he-dhamo/graphto3d/issues/12#issuecomment-1256978552
